---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: farmanahmed888
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "farmanahmed888/scientific_calculator"
        source: pull
        tag: "latest"
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
      when: ansible_facts['os_family'] == "Debian"

    - name: Running container
      shell: /usr/local/bin/docker run -it -d --name scientific_calculates farmanahmed888/scientific_calculator:latest
